### ISSUE TITLE
slider is broken in sample page

### ISSUE THREAD

**Issue by donhatch** [jotform/before-after.js#10]
Commit 76fe500 broke the slider functionality in sample.html for me:
the slider slides but the images don't change.
@hugoam 's pull request #9 fixes it.

**Comment by donhatch** [comment]
Actually, in order to see the fix, I also have to change sample.html to load before-after.js from the current directory instead of from https://cdn.jotfor.ms/before-after/before-after.min.js.
I'm confused-- shouldn't the sample html page load the local before-after.js?

**Comment by tatarjr** [comment]
Closed - pr #9

**Comment by tatarjr** [comment]
solved with pr #9

**Comment by tatarjr** [comment]
@donhatch We provide a link to the cdn to make it easier for people to use, but I'll update the sample to include both examples.
