### ISSUE TITLE
Drag conflict with Slick.js

### ISSUE THREAD

**Issue by yeomann** [jotform/before-after.js#8]
Hi great plugin man! Really nice. Unfortunately, If i have any slider from slick.js on same page along before-after element. Then upon dragging handle of before-after element  left and right. I came to realize that slider is also going left and right. Even after leaving handle of before-after element, It seems that slick slider is still following left and right drag event of mouse. 
Here have a look i create codepen for you [http://codepen.io/yoeman/pen/yVBBjP](http://codepen.io/yoeman/pen/yVBBjP)

**Comment by yeomann** [comment]
Though after spending some time, i came up with this below solution:

```
var beforeafter_elem = $('.ba-slider'); //class of before-after-element
        var slickslider_elem = $('.slick__multitem-Con'); //class of slick slider element
        // var slickslider_elem = $('.slick__multitem-Con').slick('getSlick');
        function slickslider_ondrag(e) {
            slickslider_elem.slick("slickSetOption", "draggable", true, false);
        }
        function slickslider_offdrag(e) {
            e.preventDefault();
            slickslider_elem.slick("slickSetOption", "draggable", false, false);
        }
        if (beforeafter_elem.length && slickslider_elem.length) {
            // beforeafter_elem.on({'click mousedown touchstart' : slickslider_offdrag}, {'mouseup touchend': slickslider_ondrag});
            beforeafter_elem.on({
                'mousedown mouseenter' : function(e) {
                    $('.slick-list').removeClass('draggable');
                    slickslider_elem.slick("slickSetOption", "draggable", false, false);    
                    console.log('%c mouse in', 'background: red; color: #FFF');
                },
                'mouseup mouseleave' : function(e) {
                    e.preventDefault();
                    setTimeout(function() {
                        slickslider_elem.slick("slickSetOption", "draggable", true, false);
                        // $('.slick-list').addClass('draggable');
                    }, 250);
                    console.log('%c mouse out', 'background: yellow; color: #000'); 
                }
            });
        } 
```

everything works fine. Desired output was achieved even with unexpected error, thrown by before-after.js. some where these lines
`on("mousemove touchmove",function(t){var n=t.pageX?t.pageX:t.originalEvent.touches[0].pageX;`
and error is
`Uncaught TypeError: Cannot read property '0' of undefined`

**Comment by tatarjr** [comment]
Hey yeomann, 

I just took a quick look this seems like it was caused by both plugins using the `draggable` class to manipulate elements. You can fix this by assigning a different class on your local copy of the before-after.js. So something like `ba-draggable` instead of `draggable`.

I'll update the plugin this weekend and add a prefix to the draggable and resizable classes to avoid future conflicts.

**Comment by yeomann** [comment]
@tatarjr  thank you for your effort!
